name: "Read file contents"

on: [push, pull_request]

jobs:
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "C:\Users\m.mahmoud\Github_Projects\30th_January_2023_Project\NAME.txt"

      - name: File contents
        run: echo "${ steps.read_file.outputs.contents }"
